set ECHO OFF
set pages 0
set HEADING ON
set LINESIZE 2048
set PAGESIZE 2000
set TERM OFF
set TRIMS ON
set colsep ,

SELECT
SID,
TO_CHAR(START_TIME,'yyyy/mm/dd hh24:mi:ss') START_TIME,
TO_CHAR(LAST_UPDATE_TIME,'yyyy/mm/dd hh24:mi:ss') LAST_UPDATE_TIME,
MESSAGE,
ROUND(SOFAR/TOTALWORK*100,2) "COMPLETE(%)",
TIME_REMAINING from V$SESSION_LONGOPS
WHERE OPNAME LIKE 'RMAN%'
AND OPNAME NOT LIKE '%aggregate%'
AND TOTALWORK != 0
AND TIME_REMAINING NOT LIKE '0'
ORDER BY START_TIME;
